### ISSUE TITLE
Can't preview notes in horizontal mode

### ISSUE THREAD

**Issue by Exkywor** [seanlowe/obsidian-timelines#10]
Hi, I was trying to get this to work today and managed to have the vertical timeline working. However, in the horizontal mode, I can't make it show a preview of the note when I hover/click/control click on an event, as shown in your example.

This is what I get:
![image](https://github.com/seanlowe/obsidian-timelines/assets/46603136/93b3c458-f7b3-42b1-9461-799c134a08cc)

No matter where I click on the event, I can't get it to display its info or jump to its note, in the horizontal mode.
If I double-click on the event it sort of glitches and displays the thumbnail inside the event box for like half a second.
I had a similar issue with the original plugin, btw.

**Comment by seanlowe** [comment]
Yeah, this is an existing issue I've been trying to triage. This functionality works a lot better in the front matter update I've been working on for the past couple weeks. When that functionality gets released, this should work as expected.

**Comment by Exkywor** [comment]
Awesome!

**Comment by ReconVirus** [comment]
> Yeah, this is an existing issue I've been trying to triage. This functionality works a lot better in the [front matter update](https://github.com/seanlowe/obsidian-timelines/pull/9) I've been working on for the past couple weeks. When that functionality gets released, this should work as expected.

attach a href link to the <a> of the title

**Comment by seanlowe** [comment]
Was just testing this on the #9 PR. Works pretty splendidly. Hope to have that merged in soon.

**Comment by Exkywor** [comment]
Sounds awesome! Can't wait for it to be ready so I can add all of my notes from my history deck from Anki :D

**Comment by Exkywor** [comment]
It's fixed now and works pefectly!
