### ISSUE TITLE
Turn Timeline-Event (Frontmatter) into HTML Timeline-Event

### ISSUE THREAD

**Issue by Ric16Fr** [seanlowe/obsidian-timelines#109]
Hey there,
first of all, lots of thanks, I really appreciate your extension. I use them a lot for writing fictional novels.
The Frontmatter Event in this scenario is often used by myself for ordering information and the HTML event then, to see the events on the timeline.

I just have one feature suggestion:
When I am inserting a new Event (Frontmatter) is not displayed on my timeline. I have to insert a HTML event as well for it to be displayed.
Its not a big deal, however the Data inserted into the Frontmatter event is not automatically taken over to the HTML event. Therefore, I have to copy all the data manually then which is a bit annoying. 

Is there a feature planned, that the data is copied automatically? Or that Frontmatter events are as well displayed on the timeline?

If not, I'll maybe try to implement the first one for myself as an executable action and send you a PR then.

Thanks for informing me and for your great work!

**Comment by Ric16Fr** [comment]
Hey, thanks for the fast answer. I've tried that but it seems to doesnt work. Dont know if I forgot to set something up though, thats why I included a test Vault, if you want to take a look on it. 
Thanks in advance:

[Test Timelines.zip](https://github.com/user-attachments/files/17992048/Test.Timelines.zip)

**Comment by seanlowe** [comment]
Hey, I think I see the issue:

![differences in codeblocks](https://github.com/user-attachments/assets/08868da3-fe4e-463c-869a-df39304125f0)

each codeblock argument must be on its own line for the plugin to properly parse out what it needs to do

**Comment by Ric16Fr** [comment]
Ohh yes, lovely, now it works!
Thanks for the fast response, then the frontmatter timeline is exactly what I need!
