### ISSUE TITLE
Need help to install (can't render timeline)

### ISSUE THREAD

**Issue by Didie9** [seanlowe/obsidian-timelines#11]
Hey thanks for updating this plugin!

I'm trying to get it to work, but I can't render the timeline.
- I have the tags (timeline and test)
- I made an event
- I render the timeline

Source mode:
![timelines_source](https://github.com/seanlowe/obsidian-timelines/assets/9837048/aaa95b7d-0191-4d5f-b372-87e6eb09cc75)

Read mode:
![timelines_read](https://github.com/seanlowe/obsidian-timelines/assets/9837048/e570bb3c-6e32-4ba8-b55c-306885054df4)

I wasn't sure how to install the forked version of the plugin. I disabled the original plugin and copy/pasted the obsidian-timelines-main.zip in the .obsidian/plugins folder.

The main.json and style.css were missing from the main code, and I downloaded them from your latest release 1.1.1
![image](https://github.com/seanlowe/obsidian-timelines/assets/9837048/764a20e6-a95e-4ea1-92bf-cd1f114d70cf)

I'd love to use your version, any help would be appreciated!

**Comment by ReconVirus** [comment]
delete everything

download his 
- main.js
- manifest.json
- styles.css 

put those in a folder called timelines-revamped

move that folder into .obsidian/plugin/ folder where all your other plugins are in 

turn it on via settings

make you your div layot looks like this, everything should be on its own line. and use single quotes ' not double "
```ssh
<div
class='ob-timelines'
data-title='My Test'
date-description='New Event'
data-color='orange'
data-type='range'
data-start-date='2020-10-10-00'
data-end-date='2020-10-15-00'
>
</div>
```

for the timeline render block always use timeline as a base tag, anything else acts more like filters for the timeline tag

```
  ```ob-timeline
  timeline, test
  ```
```

**Comment by Didie9** [comment]
It works! Thanks :)
