### ISSUE TITLE
How to place events on the same row in horizontal timeline?

### ISSUE THREAD

**Issue by WTCJEd** [seanlowe/obsidian-timelines#113]
Hello,

I found that in the horizontal timeline that events can be placed on the same row, such as the third event and fifth event, then the second event and fourth event, as shown in the image. ![image](https://github.com/seanlowe/obsidian-timelines/blob/main/docs/assets/images/horizontal_example.png)

I went through the docs but could not find how to do so. I also tried <span> but it renders the same as <div>. How to place events on the same row in the horizontal timeline? Thanks in advance.

**Comment by dorjor** [comment]
Here is just my observation: If the "range" events don't overlap in their time period that they describe, they are placed on the same row. Multiple overlapping events are place on top of each other.

**Comment by WTCJEd** [comment]
> Here is just my observation: If the "range" events don't overlap in their time period that they describe, they are placed on the same row. Multiple overlapping events are place on top of each other.

Thank you! Play around with it again. Initially, my ranges were rendered into separate rows because the end date of my first event and the start date of my second event were too close together.
