### ISSUE TITLE
[New Feature] Override tags defined on the page with a new attribute tags

### ISSUE THREAD

**Issue by Didie9** [seanlowe/obsidian-timelines#12]
Hello, I'd like to be able to override the tags in the note inside the <div snippet.

I would like to create multiple events inside the same page. But these events would be rendered in different timelines.
For example, I have **Timeline A** and **Timeline B**.

**Event 1** should only be rendered in **Timeline A**. [tag: hello]
**Event 2** should only be rendered in **Timeline B**. [tag: world]
Because tags are set for the whole page and all the events defined within it, the example above is not possible.
**Event 1** and **Event 2** would both be rendered in **Timeline A** and **B**, because the page contains all the tags [timeline, hello, world].

I'd like to be able to override the tags on the page inside the snippet so that the event only uses the tags specified inside of it. Like an additional attribute (optional) **_data-tags='hello'_** (ignores "world" that is set in the note, but outside of the snippet)

Thanks!

**Comment by seanlowe** [comment]
Thanks for opening an issue. I think this is a great idea. I'll try to get this in the next release.

**Comment by seanlowe** [comment]
I've merged this into main and it should have created a new release for you to use. Once I get the frontmatter stuff in, I plan to follow Obsidian's publishing guide so you won't have to jump through hoops to install this plugin.

You can add the optional attribute `data-tags` to any event and it should work for you. If it does not, feel free to comment here or open a new issue.

Thanks for the suggestion!

**Comment by DianaProbst** [comment]
So is it the case that override tags have to be a subset of the tags in the main note?
