### ISSUE TITLE
Requesting additional help

### ISSUE THREAD

**Issue by DevangPatelR** [seanlowe/obsidian-timelines#16]
Hi Sean,

I am unable to use this plugin at all. I am probably doing something completely wrong or I wasn't able to install this on my local correctly. In either case, can I request a step-by-step video tutorial which would be very helpful.

Thanks,
Devang

**Comment by seanlowe** [comment]
Hey, thanks for opening an issue! The process to install this is a bit convoluted at the moment since I haven't officially published this plugin. I'm currently working on the finishing touches to #9, after which I plan on following Obsidian's publishing guide.

I'm not sure how long that takes so once I get the PR merged in, I'll come back and try to get you some additional info on how to install this plugin manually.

In the mean time, would you be able to walk me through your process, and any errors you encountered when installing the plugin?

Thanks!

**Comment by DevangPatelR** [comment]
Here are the steps:
- I downloaded your Repo to my local.
- npm install
- npm run dev (this created main.js in dist folder)
- Executed following command from build.sh file (these gets manifest.json, and styles.css in dist folder)
    - npx sass ./styles/global.scss ./dist/styles.css --no-source-map
    - cp ./manifest.json ./dist/manifest.json
- I copied all these 3 files from "\dist" to "\.obsidian\plugins\obsidian-timelines".
- Ctrl + P >> Reload app without saving.
- Setting >> Community Plugins >> made sure that "Timelines (Revamped)" is enabled.

Now if I try to switch to preview mode (Ctrl + E), timeline is not displaying. Even though same is working for Older Timeline version (Darakah). But I am using same example as I found in [Darakah youtube example](https://www.youtube.com/watch?v=_gtpZDXWcrM).

**Comment by seanlowe** [comment]
Hey so I created `npm run dev` so I could run that and have it automatically copy the files I need into *my* test vault. If you take the path of the vault you're using and put it in that file, it should work as well.

A couple comments here:
- I am unfamiliar with the Ctrl + P command. What OS are you running on?
- are you following Darakah's YouTube example exactly? There have been changes to the code and keys required in order for timelines to display that were pointed out in the Readme.
- if you push Ctrl+Shift+i, while on the note with your timeline, do you see any red console errors? I am aware of a bug related to the plugin not working when the vault is first opened that I am looking into
- have you tried using the BRAT plugin to install this plugin? I only recently learned about it but it's supposed to make manually installing plugins a lot easier

**Comment by DevangPatelR** [comment]
Please find my response inline -

> * I am unfamiliar with the Ctrl + P command. What OS are you running on? - ***Windows, and I was going to try it on my Linux Machine later today.***
> * are you following Darakah's YouTube example exactly? There have been changes to the code and keys required in order for timelines to display that were pointed out in the Readme. - ***I was following it exactly, I haven't made any changes. I glanced through readme and it looked similar. I will read it thoroughly now.***
> * if you push Ctrl+Shift+i, while on the note with your timeline, do you see any red console errors? I am aware of a bug related to the plugin not working when the vault is first opened that I am looking into. - ***I didn't knew about this. This is very helpful. Yes, I am getting error.***
> <img width="278" alt="Screenshot 2023-12-13 113607" src="https://github.com/seanlowe/obsidian-timelines/assets/57112948/f480f74f-d279-4d97-8d84-b95448e165fa">
>
> * have you tried using the BRAT plugin to install this plugin? I only recently learned about it but it's supposed to make manually installing plugins a lot easier - ***I didn't knew about this either, I will give it a try.***

I am fairly new to Obsidian and its plugin development. Thank you so much for your help. I really appreciate it.

**Comment by seanlowe** [comment]
Were you able to get it working?

**Comment by DevangPatelR** [comment]
Yes, its working. Though I still need to make some changes but overall its working.

**Comment by seanlowe** [comment]
Awesome. I'm going to close this issue. If you run into any other problems, feel free to open up a new issue.
