### ISSUE TITLE
BCE Dates

### ISSUE THREAD

**Issue by Exkywor** [seanlowe/obsidian-timelines#20]
So, today I was adding some history events to my timeline, and I'm seeing that the `start-date` property does not allow for dates before the year 0. Is there anything I'm missing here?

**Comment by seanlowe** [comment]
I was just about to respond and ask for more information. I'm guessing you figured it out? Would you mind putting the information here for posterity?

Thanks!

**Comment by Exkywor** [comment]
It seems the issue is not closed xD
I'm using the frontmatter to assign the properties, but cannot get dates before year 0 to display.

I'm trying this, but it doesn't show in the timeline
![image](https://github.com/seanlowe/obsidian-timelines/assets/46603136/2e621a4c-7d6b-4936-8409-8ffecf265311)

**Comment by ReconVirus** [comment]
use the date formate YY-MM-DD_HH so something like -0300-01-01-00 

> It seems the issue is not closed xD I'm using the frontmatter to assign the properties, but cannot get dates before year 0 to display.
> 
> I'm trying this, but it doesn't show in the timeline ![image](https://private-user-images.githubusercontent.com/46603136/290584048-2e621a4c-7d6b-4936-8409-8ffecf265311.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NzIxNTUsIm5iZiI6MTcwMjY3MTg1NSwicGF0aCI6Ii80NjYwMzEzNi8yOTA1ODQwNDgtMmU2MjFhNGMtN2Q2Yi00OTM2LTg0MDktOGZmZWNmMjY1MzExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDIwMjQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5MjNkNmJmNDgzYzhlNjZjNjhkMjQ1MDljMWU4MTc3ZWFlYmIyYTUyMzBhODI5MGVmMDg3NWNhYzBmYjcwNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TmROd8SSpsyJLCwzN8LG3vuxiSSaAjXJ_X67kU3FrLs)

**Comment by seanlowe** [comment]
The latest pushes I made enables you to put basically anything you want as your date string. If all you know about the date is the year (-300), then you can put that and the plugin internally sorts it all out for you, so that shouldn't be an issue. I'm more wondering what the timeline codeblock looks like when you try to render it. Does it display a timeline but there are no events, or just this particular event is missing?

**Comment by Exkywor** [comment]
Thanks, gonna try it in a sec.
Right now just the event is missing when I had one with a BCE date.

**Comment by seanlowe** [comment]
Could you paste in the contents of the codeblock you are using to render your timeline?

Another trick I use is to try rendering a vertical timeline (static or not) because there's no timeframe involved in those. If the vertical doesn't render the event, then we have a larger issue.

**Comment by Exkywor** [comment]
I tried a vertical one, and it does show events with negative dates, so the issue is only with the horizontal one.

```ob-timeline
tags=history
startDate=-3000
endDate=2100
divHeight=500
minDate=-3000
maxDate=2100
type=flat
```

**Comment by ReconVirus** [comment]
> ```
> type=flat
> ```

Note: Acceptable values for data-type are:

    background, best used for time periods
    box
    point, which is exactly what it sounds like, and
    range

**Comment by Exkywor** [comment]
All of those render vertically, with no noticeable difference between them.

**Comment by seanlowe** [comment]
@ReconVirus Note that I recently added a `type=flat` key that only exists on the timeline codeblock, so this is correct. The `background`, `box`, `point` and `range` type values all go on the events (HTML / Frontmatter).

@Exkywor I'll look into this and get back to you soon!

**Comment by Exkywor** [comment]
Any updates?

**Comment by seanlowe** [comment]
Hey @Exkywor, still looking into this. For now, this is a limitation of the library (vis-timeline) I use to generate the horizontal timeline. I've made a few changes locally that allows the time range inside the timeline to be negative but no progress yet on getting the events to render. Part of that is due to the way we need to parse negative inputs into a real date and Moment (shipped with Obsidian) isn't great at it.

I'm looking into alternatives for both rendering the timeline as well as DateTime libraries that might have more functionality.

**Comment by vadhmln** [comment]
> use the date formate YY-MM-DD-HH so something like -0300-01-01-00

yes, to render dates with negative values you should make startDate: -0300-01-01-00 whith hours, otherwise it doesn't render.

**Comment by Exkywor** [comment]
> > use the date formate YY-MM-DD-HH so something like -0300-01-01-00
> 
> yes, to render dates with negative values you should make startDate: -0300-01-01-00 whith hours, otherwise it doesn't render.

Holy cow, the solution was right there all along! This actually fixes it!

**Comment by Exkywor** [comment]
I totally missed the first time this was suggested
