### ISSUE TITLE
Maximum Amount of Years Caps at just 275 000

### ISSUE THREAD

**Issue by wanwindwalker** [seanlowe/obsidian-timelines#25]
I'm trying to create a historical timeline on the span of 3 million years, would it be possible to change the maximum cap?

**Comment by seanlowe** [comment]
Yeah, looks like this is possible, would just have to hook it up.

| option name | type | default | description |
|-------------|------|---------|-------------|
| max |	Date or Number or String or Moment |	none |	Set a maximum Date for the visible range. It will not be possible to move beyond this maximum.|
| min |	Date or Number or String or Moment |	none |	Set a minimum Date for the visible range. It will not be possible to move beyond this minimum.|

**Comment by seanlowe** [comment]
Did some more looking into this. I am already using the min/max options when creating the horizontal timeline. Unfortunately, while the docs don't say there is a limit, you are right in that it caps at 275,000. This is a problem with the vis-timeline, unfortunately.
