### ISSUE TITLE
Raise Zoom out limit cap to allow to display timeline range of more than 100 000 in one image

### ISSUE THREAD

**Issue by wanwindwalker** [seanlowe/obsidian-timelines#28]

**Comment by seanlowe** [comment]
options listed on #30 might help with this as well

**Comment by seanlowe** [comment]
This is partially the same as #30, so I'm closing it at the same time as I close that issue.

By passing in an extremely large number for the timescale, you can get close to what you want in this issue but it's a limitation of the vis-timeline library that it's not something I can really fix too well. In my experience, the most I could get it to display at one time was around 50,000 years and that was with the window full-screened on an ultrawide monitor. Unfortunately, if you zoom out too far the time axis values get all screwy, so it's really dependent on how large your window is.
