### ISSUE TITLE
Implement Vertical Movement in Horizontal Timeline

### ISSUE THREAD

**Issue by wanwindwalker** [seanlowe/obsidian-timelines#31]

**Comment by seanlowe** [comment]
Not sure that this is possible, but the docs do have this option, even though I'll have to test if this does what we want or not. The bit about "group list" in the description is what makes me uncertain this option will work.

| option name | type | default | description |
|-------------|------|---------|-------------|
|verticalScroll|	Boolean|	false|	Show a vertical scroll on the side of the group list and link it to the scroll event when zoom is not triggered. Notice that defining this option as true will NOT override horizontalScroll. The scroll event will be vertically ignored, but a vertical scrollbar will be visible|

**Comment by seanlowe** [comment]
https://visjs.github.io/vis-timeline/examples/timeline/other/verticalScroll.html

**Comment by seanlowe** [comment]
I'm going to move this ticket to live under ticket #26 because this sounds like kind of the fix for the other one
