### ISSUE TITLE
In Horizontal Timeline Hover Range Event to highligt its connecting line and point on the timeline and vice versa

### ISSUE THREAD

**Issue by wanwindwalker** [seanlowe/obsidian-timelines#34]

**Comment by seanlowe** [comment]
Just to make sure I understand.

When hovering a "Range" event on the horizontal timeline, you'd like the connecting line and the point on the timeline to highlight the same as the event box does?

**Comment by wanwindwalker** [comment]
Yes like that, because when events at relatively the same time close to each other are stacked on top of each other and it's hard to differentiate the connecting lines since they become very long

**Comment by seanlowe** [comment]
This has been added in release 2.1.7

Any event that has a line connecting it to the time axis should now have all its parts highlighted when the cursor hovers over it.

Let me know if you run into any problems. Thanks!
