### ISSUE TITLE
Make example files

### ISSUE THREAD

**Issue by SUNsung** [seanlowe/obsidian-timelines#42]
Make several separate files with an example implementation and screenshots of how it should work. It is unclear how to use it.
The README didn't help, nothing from it worked for me. Fresh obsidian, turned off all plugins except the timeline.

The old version also does not work (https://github.com/Darakah/obsidian-timelines), are you sure you support obsidian v1.5.12??

**Comment by seanlowe** [comment]
I agree the documentation is a little wonky. I'll put in some effort to write better documentation soon.

Specifically in your case, where did you need help? We can see if I can't help you get it running.

**Comment by seanlowe** [comment]
Alright, I have written new and better documentation located at [seanlowe.github.io/obsidian-timelines](https://seanlowe.github.io/obsidian-timelines/docs). Have a read through the new docs.

I wrote some very simple guides on both vertical and horizontal timelines. Hopefully this has enough information to get you up and running. If you have any questions, please let me know!

**Comment by seanlowe** [comment]
Did you have a chance to take a look at the new documentation?

**Comment by seanlowe** [comment]
Hey, I'm gonna close this issue. If you end up having any problems, don't hesitate to create a new issue. Thanks!
