### ISSUE TITLE
[Bug] Flat timeline does not render

### ISSUE THREAD

**Issue by F4zeless** [seanlowe/obsidian-timelines#45]
Pretty much the issue in the title. 

I am creating a timeline of roughly 40-50 events atm. No pictures, just plain text and links. The timeline renders all the events in the default vertical style. However, when I use the type = flat argument it does not render anymore.

Sorry if notation of issue is untypical. Its my first time using github.

**Comment by seanlowe** [comment]
No worries, thanks for creating the issue - hopefully we can help figure this out. Could you post an example of what your events (are you using frontmatter or HTML?) and what your `ob-timeline` codeblock looks like?

**Comment by F4zeless** [comment]
There are 2 errors at the end of the log

vis-timeline-graph2d.js:11284 Uncaught (in promise) TypeError: Unknown item type "red"
    at eval (vis-timeline-graph2d.js:11284:17)
    at Array.forEach (<anonymous>)
    at ItemSet._onUpdate (vis-timeline-graph2d.js:11250:9)
    at ItemSet.setItems (vis-timeline-graph2d.js:11098:12)
    at Timeline.setItems (vis-timeline-graph2d.js:15104:34)
    at new Timeline (vis-timeline-graph2d.js:15020:12)
    at TimelineBlockProcessor.eval (block.ts:413:22)
    at Generator.next (<anonymous>)
    at eval (tslib.es6.js:121:71)
    at new Promise (<anonymous>)
eval @ vis-timeline-graph2d.js:11284
_onUpdate @ vis-timeline-graph2d.js:11250
setItems @ vis-timeline-graph2d.js:11098
setItems @ vis-timeline-graph2d.js:15104
Timeline @ vis-timeline-graph2d.js:15020
eval @ block.ts:413
eval @ tslib.es6.js:121
__awaiter @ tslib.es6.js:117
buildHorizontalTimeline @ block.ts:328
eval @ block.ts:498
fulfilled @ tslib.es6.js:118
Promise.then (async)
step @ tslib.es6.js:120
eval @ tslib.es6.js:121
__awaiter @ tslib.es6.js:117
eval @ main.ts:31
t.initDOM @ app.js:1
t.toDOM @ app.js:1
t.sync @ app.js:1
e.sync @ app.js:1
(anonymous) @ app.js:1
e.ignore @ app.js:1
t.updateInner @ app.js:1
t.update @ app.js:1
e.update @ app.js:1
dispatchTransactions @ app.js:1
e.dispatch @ app.js:1
(anonymous) @ app.js:1
setTimeout (async)
Ls @ app.js:1
ds.blur @ app.js:1
e.runHandlers @ app.js:1
e.handleEvent @ app.js:1
vis-timeline-graph2d.js:11284 Uncaught (in promise) TypeError: Unknown item type "red"
    at eval (vis-timeline-graph2d.js:11284:17)
    at Array.forEach (<anonymous>)
    at ItemSet._onUpdate (vis-timeline-graph2d.js:11250:9)
    at ItemSet.setItems (vis-timeline-graph2d.js:11098:12)
    at Timeline.setItems (vis-timeline-graph2d.js:15104:34)
    at new Timeline (vis-timeline-graph2d.js:15020:12)
    at TimelineBlockProcessor.eval (block.ts:413:22)
    at Generator.next (<anonymous>)
    at eval (tslib.es6.js:121:71)
    at new Promise (<anonymous>)

Seems to have to do with red as color?
I have issues with copying the whole log as its to long.

**Comment by seanlowe** [comment]
Hmm.. This tells me what file the error is occurring in (`block.ts`) and what function (`buildHorizontalTimeline`) but not where the error is occurring.

Could you provide one or two examples of the frontmatter in your notes so I can recreate the problem?

**Comment by F4zeless** [comment]
example background

---
description: 
Coalition Parties:
  - "[[SPÖ]]"
  - "[[ÖVP]]"
Opposition Parties:
  - "[[FPÖ]]"
color: DarkRed
startDate: 1997-01-28
endDate: 2000-02-04
type: background
era: 
path: 
tags:
  - Government
  - timeline
showOnTimeline: true
---



example event:

---
title: 
description: 
color: red
type: box
startDate: 1971-10-10
endDate: 1971-10-10
era: 
path: ""
tags:
  - federal
  - national-assembly
  - timeline
  - Government
showOnTimeline: false
---

**Comment by F4zeless** [comment]
I Just found the issue myself. By accident i attributed one event as type = red instead of type = box. I am not sure why this is not an issue with vertical rendering. Maybe the type is not considered? Nevertheless thankfull for your time!

**Comment by seanlowe** [comment]
As for why it does not affect the vertical timeline, really the only keyword that matter to the vertical one (for right now) is `tags`. None of the rest of them do anything for the vertical timeline.

Glad you figured it out. I do think the malformed / bad input notice should be bumped up in priority lol. Would have made finding this a lot easier for you.
