### ISSUE TITLE
Refined Horizontal Timeline View

### ISSUE THREAD

**Issue by gleyconJ** [seanlowe/obsidian-timelines#49]
ob-timeline
tags=now
type=flat
startDate=2024
endDate=2025
zoomInLimit=day

I'm not able to get the:

startDate=2024
endDate=2025

Have more configuration to display only 3 months instead of 12. I've already tried

startDate=2024-11-01
endDate=2025-01-01

startDate=2024/11/01
endDate=2025/01/01

Nothing works. Why?

**Comment by seanlowe** [comment]
That would be an oversight on my end. I'll push a release for this fix soon. Thanks for bringing it to my attention!
