### ISSUE TITLE
Feature suggestion, time spans in vertical timelines

### ISSUE THREAD

**Issue by enigmartyr** [seanlowe/obsidian-timelines#52]
More of a suggestion than a request, I've kinda been tinkering away at this. Not sure how it ought to handle overlapping time windows if at all but for simple spans with a few events inside this seems to work. If this is in-line with your vision for the plugin I can continue working on it

![image](https://github.com/seanlowe/obsidian-timelines/assets/115123556/5ff371d3-a739-4ac6-a93b-4d018dc5d3bb)
![image](https://github.com/seanlowe/obsidian-timelines/assets/115123556/a79f4118-df20-453f-8ae8-0a401f23add8)

**Comment by seanlowe** [comment]
This is pretty sick. Yeah, go ahead and tinker to your hearts desire and we can collab on this once you've got it where you want it.
