### ISSUE TITLE
a little problem

### ISSUE THREAD

**Issue by chenghuang-coder** [seanlowe/obsidian-timelines#56]
Dear seanlowe,

First of all, thank u for this great plugin!

There is a little problem:
in the main page of github release, you write:
`I've written a brand new GitHub Pages docs site for Timelines (Revamped) at https://seanlowe.github.io/. Go check it out!`

but by clicking the `https://seanlowe.github.io/` it cannot be directed to the right page, it seems like u need complete it with the suffix`obsidian-timelines`

Have a good day~

**Comment by seanlowe** [comment]
Yep! That is totally correct. I have the right link in the description either at the top (on mobile) or on the right (on desktop). 

There'll be a release for some other stuff that's been in the works soon so I'll tag this fix onto one of those.

Thanks for bringing it up!

**Comment by seanlowe** [comment]
Will be handled in PR: #57
