### ISSUE TITLE
[Feature - Horizontal] Implement timeline groups / subgroups

### ISSUE THREAD

**Issue by zzxii** [seanlowe/obsidian-timelines#62]
If I have 2 events that have overlapping dates (event1a and event 2a) and they have following events (event1b and event2b) with overlapping dates. The vertical sorting and vertical ordering seems to be unorganized. Is there a parameter to set the sort, if not it seems to be inconsistent. Zooming in and out also causes the events to move in their vertical location. #Bug? Edit: grammar.
![Timelines event sorting horizontal](https://github.com/seanlowe/obsidian-timelines/assets/49501652/7051fc48-45f9-4bcc-b63d-cf6d9dd124d9)

**Comment by seanlowe** [comment]
Just for clarification, by "vertical sorting" I'm understanding you're referring to something like the "weight" of the item -- what items get rendered on bottom versus above?

The library in question, [vis-timeline](https://github.com/visjs/vis-timeline), has a kinda-sorta-half similar functionality through the use of groups and subgroups but so far as I am aware, there's no ability to influence how the events are rendered otherwise.

**Comment by seanlowe** [comment]
Unfortunately yes. vis-timeline is pretty much the _only_ library available to create timelines like this and from looking at the docs, I see nothing that would allow someone to manually order the events vertically. From what I found on the previous iteration of vis-timeline, there was an [issue](https://github.com/almende/vis/issues/325) that talked about using subgroups to put things on the same level but not sure how involved this is.

**Comment by zzxii** [comment]
@seanlowe Thanks for the link. Could you post an example of what the frontmatter property would be for the "groups"? 
I tried groups=group1 at the end of my front matter with no luck.

**Comment by zzxii** [comment]
Thank you for the quick replies. For the time being can we change this thread to be a "feature request" to add the group function to your plugin? In the mean time I will look to tinker on my end. No promises that my results will result in a anything positive.

**Comment by seanlowe** [comment]
Sure thing! Thanks for creating the issue! If you end up tinkering on it, let me know how it goes. I'll comment here if I start to build it into the plugin.

**Comment by mcogando** [comment]
I'm just "bumping" this, as it's a feature I would also really would enjoy. My timelines are all over the place.
If anyone has found a workaround, provisory or definitive, please let me know.

![image](https://github.com/user-attachments/assets/cca10775-4512-4bc9-98bb-045d4ff409bb)

**Comment by seanlowe** [comment]
I'm currently working on implementing this for the next release. I have primary groups working and working on subgroups. Then it's just a bit of QA to make sure everything works as intended and I didn't cause any regressions and it should be good to go!

I'm thinking at max a couple more weeks for it to be ready for release.
