### ISSUE TITLE
Custom attributes on timeline nodes

### ISSUE THREAD

**Issue by tomatau** [seanlowe/obsidian-timelines#63]
I'd like to be able to attach custom attributes to the nodes that are rendered so that I can target them for custom styling. Such as adding a specific coloured border or underline or something.

Either `className` or`data-*` should be enough.

This could also be a hook for custom JavaScript that targets nodes.

This is most valuable to me in the horizontal view as there is less information displayed and visual indicators could add a lot.

Also, I see mention of the swimlanes for grouping items - that would be rad too

**Comment by seanlowe** [comment]
I'm going to focus on the custom attribute in this issue. If we come back around to the swimlanes, perhaps we can open a new issue specifically for that.

**Comment by seanlowe** [comment]
This is added to release 2.2.5

**Comment by seanlowe** [comment]
Ah, yes, my bad. Yes I have added information on the new field in the docs but essentially it's just "data-classes" and then you can create an obsidian snippet to store your css in. It works right off the bat with the vertical timelines. With horizontal ones you have to do

```css
.your-super-class > div > div > a {... }
```

If you want to target the font of the events on the horizontal timeline.

Let me know if this doesn't make sense and I can come back and try to clean up my answer

**Comment by gleyconJ** [comment]
> Ah, sim, o meu mal. Sim, adicionei informações sobre o novo campo nos documentos, mas essencialmente são apenas "classes de dados" e então você pode criar um trecho de obsidiana para armazenar seu css. Funciona logo de cara com as linhas do tempo verticais. Com os horizontais você tem que fazer
> 
> ```css
> .sua superclasse > div > div > a {... }
> ```
> 
> Se você deseja direcionar a fonte dos eventos na linha do tempo horizontal.
> 
> Deixe-me saber se isso não faz sentido e posso voltar e tentar limpar minha resposta

I am a novice user. So I prefer to just use the functions in Frontmatter. I have never used the other way to insert metadata. Apparently this function will only work if I use it in HTML mode. Would it be this? Only if it is written like this:

<div class="ob-timelines"
        data-title=""
        data-description=""
        data-color=""
        data-type=""
        data-start-date=""
        data-end-date=""
        data-era=""
        data-path=""
        data-tags="">
        New Event
</div>

**Comment by seanlowe** [comment]
Ah, I forgot to add the new attribute to the insert commands. I'll push up a release this evening when I have some time. Sorry about that!

**Comment by seanlowe** [comment]
Well it wasn't "this evening" but I did eventually get this fixed. In release 2.2.6. Should be live in a bit

**Comment by profxavr** [comment]
is there an example anywhere of how to format the vertical timeline? I expected it to use the "color" attribute, but it seems only the horizontal timeline does.

**Comment by seanlowe** [comment]
@profxavr Currently the vertical timeline does not utilize the `colors` attribute for events. It's on my to-do list
