### ISSUE TITLE
[Feature] A Hotkey or command to redraw the timeline after edit

### ISSUE THREAD

**Issue by QuantumBob** [seanlowe/obsidian-timelines#74]
Currently I am editing the timeline dates using a popup window, but the only way to see these changes is to close and reopen the timeline.
It would be great if this wa auotomatic, like dataview, but I realize this is a complex issue.
BUT it wouls be great if there was a command to redraw/update the timeline which could have a hotkey attached to it.
Thanks for a great plugin!

**Comment by seanlowe** [comment]
This has been added in release 2.2.3. Should be out shortly. Thanks for opening the issue
