### ISSUE TITLE
Confused about the tags

### ISSUE THREAD

**Issue by DM-Homebrew** [seanlowe/obsidian-timelines#82]
Just downloaded obsidian and got this plug-in but not sure where to put the tags. I got everything else looking like your example.

![ob-timeline](https://github.com/user-attachments/assets/15ad3134-592c-49f3-8650-1d20ee8049c4)

I thought the tag must go in the actual event (either above or below the "Event Number One" but that didn't work then just tried putting the tags in the body of the page and that didn't work so not sure where to include that to show the event

**Comment by seanlowe** [comment]
Hey, so the tags can go either in the note body just as `#whatever-your-tag-is #timeline` or it can go in frontmatter in a "tags" field. The obsidian properties update handles this pretty well.

Personally, I don't put events in the same file as a timeline but that's just me. I don't _think_ it should cause any issues.

Example of frontmatter:
![image](https://github.com/user-attachments/assets/4edc955f-2559-49d1-8d2c-6f83ff8bcabb)


Example of tags being inside the actual note:
![image](https://github.com/user-attachments/assets/5cd0b255-8e25-4f68-9d12-6385d197c73f)

Let me know if you need any more assistance!

**Comment by DM-Homebrew** [comment]
Ok, my main issue wasnt the tag. In editing mode I had to click back into the ob-timeline code block and then exit that and it popped up, then once I went to reading mode I just had to ctrl-p and reload

**Comment by seanlowe** [comment]
Sweet, glad you got it figured out. If you run into any issues or have any suggestions for the plugin, let me know by creating a new issue. Thanks!
