### ISSUE TITLE
[Bug - Vertical] Sections of the date are visible when not provided

### ISSUE THREAD

**Issue by JiawuTian** [seanlowe/obsidian-timelines#86]
I use the following template to write my notes.
<img width="397" alt="image" src="https://github.com/user-attachments/assets/23fc4159-a75a-47cf-8826-f3032c660178">

And I use this code (NO backslas. I don't know how to display it correctly) to create timelines:
```
\```
ob-timeline
tags=timeline;MajorEvent;
\```
```

But I got the following result. I do NOT need the number after the date. How can I remove them?
<img width="647" alt="image" src="https://github.com/user-attachments/assets/d318c5f0-c557-42a5-8d17-37bfce7e55f6">

**Comment by seanlowe** [comment]
Hey, sorry. Last release must have regressed this. I'll look into this soon!

**Comment by JiawuTian** [comment]
Thank you very much! The plugin is very suit for my need. I appreciate your effort in developing obsidian-timelines!

**Comment by seanlowe** [comment]
related: #87

**Comment by seanlowe** [comment]
OK - did some digging here. I found out that when you pass all sections of the date string, year, month, day, and hour, it behaves as you'd expect. You can pass something like "2024-01-00-00" to get "2024-1" on your timeline, or you can pass "2024-00-00-00" to show only the year.

My logic fails when there are pieces of the date string missing.

If you look at this screenshot:
![image](https://github.com/user-attachments/assets/07ae49dd-2eea-425a-956c-84b37de58f8a)

You can see each of the examples I described above.

So, this is a _workaround_ but this validates that there does exist a bug and I can have a better idea of where to look for this. For now, the workaround is to simply put all sections of the date-strings. For any sections you don't want to show up, put it as 0

**Comment by seanlowe** [comment]
This is fixed in release 2.3.2

**Comment by JiawuTian** [comment]
> This is fixed in release 2.3.2

Sorry for post my problem again here.
I use the version 2.4.0 of obsidian-timelines and it seems not solve my problem I had encountered.
Why？

![Image](https://github.com/user-attachments/assets/98d6e316-7d3c-4dc5-a0ce-2c23e9b5d70b)

<img width="745" alt="Image" src="https://github.com/user-attachments/assets/ae0a1900-4a1d-4f01-ad2c-65bc12d70e89" />

![Image](https://github.com/user-attachments/assets/f10f29d1-1773-4c80-aa0b-a8bede9b9552)
