### ISSUE TITLE
My flat timeline doesn't render

### ISSUE THREAD

**Issue by sangwon9029** [seanlowe/obsidian-timelines#91]
![image](https://github.com/user-attachments/assets/7c9692e6-afee-45b4-a271-7d98d073916e)
![image](https://github.com/user-attachments/assets/4c9854f9-4332-41d2-84cb-9b5d3420c590)
![image](https://github.com/user-attachments/assets/2e593d00-4faa-43b7-b524-2418b9726ce8)
Thank you for this great plugin. 
The horizontal timeline doesn't show anything, while my vertical timeline works great. 
I've added "type=flat" but it doesn't show anything.
Please help me out!

**Comment by seanlowe** [comment]
`type=flat` only applies to the codeblock which you have done correctly.

The issue here is your `data-type=flat`

`data-type` can be any of the following values: `box` (default), `point`, `background`, and `range`.
- `background` and `range` require a start **and** end date.
